#ADMIN_USER = 'reproserver'
#ADMIN_PASSWORD = 'hackmehackme'

#AMQP_USER = ADMIN_USER
#AMQP_PASSWORD = ADMIN_PASSWORD

#S3_KEY = ADMIN_USER
#S3_SECRET = ADMIN_PASSWORD

#POSTGRES_USER = ADMIN_USER
#POSTGRES_PASSWORD = ADMIN_PASSWORD
#POSTGRES_DB = 'reproserver'
