version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    environment:
      REPROZIP_USAGE_STATS: "off"
      DOCKER_HOST: tcp://docker:2375
      REGISTRY: registry:5000
    ports:
      - 8000:8000
  minio:
    image: minio/minio:RELEASE.2019-08-29T00-25-01Z
    command: ["server", "/export"]
    environment:
      MINIO_ACCESS_KEY: ${S3_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET}
    ports:
      - 9000:9000
  registry:
    image: registry:2.6
    ports:
      - 5000:5000
  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  docker:
    image: docker:18.09-dind
    privileged: true
    command: ["--insecure-registry=registry:5000"]
