apiVersion: v1
kind: ServiceAccount
metadata:
  name: reproserver-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reproserver-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reproserver-sa-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reproserver-runner
subjects:
  - kind: ServiceAccount
    name: reproserver-sa
