apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2019-08-29T00-25-01Z"
          args: ["server", "/export"]
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: reproserver-secret
                  key: s3_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: reproserver-secret
                  key: s3_secret
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - mountPath: /export
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-host
  labels:
    app: minio
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30090
