apiVersion: v1
kind: ServiceAccount
metadata:
  name: reproserver-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reproserver-builder
rules:
- apiGroups: [""]
  resources: ["pods", "jobs"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reproserver-sa-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reproserver-builder
subjects:
- kind: ServiceAccount
  name: reproserver-sa
