apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
spec:
  rules:
    - host: server.reprozip.org
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 8000
    - host: files.server.reprozip.org
      http:
        paths:
          - backend:
              serviceName: minio-host
              servicePort: 9000
    - host: "*.web.server.reprozip.org"
      http:
        paths:
          - backend:
              serviceName: web-proxy
              servicePort: 8001
