{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name | default (include "postgres.fullname" .) }}"
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres_user: {{ "pguser" | b64enc | quote }}

  {{- /* Retrieve existing secret */}}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (.Values.secret.name | default (include "postgres.fullname" .))) | default dict }}
  {{- /* Set $password to existing data or generate a random password */}}
  {{- $password := (get (get $secret "data" | default dict) "postgres_password") | default (randAlphaNum 32 | b64enc) }}

  postgres_password: {{ $password | quote }}
{{- end }}
