---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-prom
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: web
        dns_sd_configs:
          - names:
              - web-scrape
            type: "A"
            port: 8090
            refresh_interval: 60s
      - job_name: proxy
        dns_sd_configs:
          - names:
              - proxy-scrape
            type: "A"
            port: 8090
            refresh_interval: 60s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 65534:65534 /prometheus"]
          volumeMounts:
            - name: k8s-prom
              mountPath: /etc/k8s-prom
            - name: data
              mountPath: /prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.14.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/k8s-prom/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          volumeMounts:
            - name: k8s-prom
              mountPath: /etc/k8s-prom
            - name: data
              mountPath: /prometheus
          ports:
            - name: web
              containerPort: 9090
      volumes:
        - name: k8s-prom
          configMap:
            name: k8s-prom
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 472:472 /grafana"]
          volumeMounts:
            - name: data
              mountPath: /grafana
      containers:
        - name: grafana
          image: quay.io/remram44/grafana:7.5.15-image_renderer
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            #GF_SMTP_ENABLED=true
            #GF_SMTP_HOST=ip-of-the-host:25
            #GF_SMTP_FROM_NAME=ReproServer Development
            #GF_SERVER_ROOT_URL=https://grafana.example.org/
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
          ports:
            - name: web
              containerPort: 3000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-scrape
  labels:
    app: web
spec:
  selector:
    app: web
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-scrape
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: web
      protocol: TCP
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
spec:
  ingressClassName: "nginx"
  rules:
    - host: grafana.server.reprozip.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana
                port:
                  name: web
