---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: reproserver-secret
stringData:
  postgres_user: "reproserverdb"
  # Fill those in with secret values
  postgres_password: "hackme"
  s3_key: "s3_access_key"
  s3_secret: "s3_secret_key"
  connection_token: "secret-token"
  zenodo_token: "xxx"
