{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.storage.persistentClaimName | default (include "minio.fullname" .) }}"
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.storage.claimAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
{{- end }}
