{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name | default (include "minio.fullname" .) }}"
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  s3_key: {{ "minioaccesskey" | b64enc | quote }}

  {{- /* Retrieve existing secret */}}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (.Values.secret.name | default (include "minio.fullname" .))) | default dict }}
  {{- /* Set $password to existing data or generate a random password */}}
  {{- $password := (get (get $secret "data" | default dict) "s3_secret") | default (randAlphaNum 32 | b64enc) }}

  s3_secret: {{ $password | quote }}
{{- end }}
