{{- if .Values.metricsService.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reproserver.fullname" . }}-scrape
  labels:
    {{- include "reproserver.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "reproserver.selectorLabels" . | nindent 4 }}
    server.reprozip.org/component: web
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reproserver.fullname" . }}-proxy-scrape
  labels:
    {{- include "reproserver.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "reproserver.selectorLabels" . | nindent 4 }}
    server.reprozip.org/component: proxy
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
{{- end }}
