apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reproserver.fullname" . }}-proxy
  labels:
    {{- include "reproserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reproserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reproserver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TORNADO_SHUTDOWN_TIME
              value: {{ .Values.shutdownTime | quote }}
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "reproserver.postgresSecretName" . }}"
                  key: postgres_password
            - name: POSTGRES_HOST
              value: {{ include "reproserver.postgresServiceName" . }}
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            - name: CONNECTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name | default (include "reproserver.fullname" .) }}"
                  key: connectionToken
          command:
            - "reproserver-k8s-proxy"
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
            - name: prometheus
              containerPort: 8090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
              httpHeaders:
                - name: X-Kubernetes-Probe
                  value: readiness
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
              httpHeaders:
                - name: X-Kubernetes-Probe
                  value: liveness
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
